import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import Link from "next/link";
import ThemeToggle from '../components/ThemeToggle'
import { getPages } from "@/sanity/sanity-utils";


const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pages = await getPages()
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex justify-between p-4 pb-10">

<div className='flex items-center'> <p className='text-xs'>Color Theme:</p> <ThemeToggle />
 </div>
          <div>
          <Link href='/' className="pr-2">Home</Link>
            {pages.map((page)=> (
              <Link key={page._id} href={`/${page.slug}`} className="pr-2">{page.title}</Link>
            ))}
          </div>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
